env:
  global:
    secure: GeIYpXkTpxi2l/lVmjm+2FrGO/2zTpvN3bTJDY8GEZUEXpLo+M0NGPhdIz7h1x0LzHBWOkkOnmQn0XRY2K/j2EZH6M8qBmgBAkwUekwuv/ICPij4pC+9LrTgp1d4u04E+138mUpoWsNCJMI/kuKaD1/FDdkA6GXeecKNnNn1UCd1CH3jElSf41R+hABhUHYxWwXsE7qeq8wOpFVj094kmo3DnF9vWFqzkuckkkpowKtJtDz8UzYxD68EOb3Yn1abFlqszRqevrbFDBnPNysRViJgBM2vk8Kd+Oxd8Z2MbhIzrEvGHj/AXltpfaPUyf6gUW/2fmZfrzI9afNzH1vngZBuWq5S7vFN/K2QNkmwapm4C77m5C3tuZ2hbxM4HDi8JhyArIPcRwHES7tgBvu4X2MSBdTfAGJi7HJYi/HZW+X9v/men/NNOk6MYHctp53GzrjBYtCz0GpeS+DdjY1zdVlXVPK7C6hsQrc+h3WJ/8Q7Q3FJEUXZ4T67vLvZ+Sv00XAu6MbouIRsZ5Y/5+oE6n01cUZsUVYLOhaPvxJ7AW0X8hyXDgpXfTzr8hsDBL3XFIYAsC7hZQGIAlVLSVRjopNOK5oPHBC2ttMS15jTtDKY0y6Ak/pgocH7xcbwRX0/RoEUz9pRD/uOaiuFmZR6eA3VSGqnuApL9pw/KBUI/CM=

sudo: required

language: python

python:
  - "2.6"
  - "2.7"

before_install:
  - pip install pylint
  
install:
  - pip install -r requirements.txt

script:
  - pylint ./alerter.py
